- id: zuban
  name: zuban check
  description: Run `zuban check` (default / auto-detected mode)
  entry: zuban check
  language: python
  types_or: [python, pyi, jupyter]
  pass_filenames: false
  require_serial: true
  stages: [pre-commit, manual]


- id: zmypy
  name: zuban mypy
  description: Run `zuban mypy` (mypy-compatible mode)
  entry: zuban mypy
  language: python
  types_or: [python, pyi, jupyter]
  pass_filenames: false
  require_serial: true
  stages: [pre-commit, manual]
